### ISSUE TITLE
Unable to run deepredeff

### ISSUE THREAD

**Issue by emilecg** [ruthkr/deepredeff#1]
Hi,
I tried to run deepredeff example (pred_result <- predict_effector(input = bacteria_fasta_path, taxon = "bacteria")) after the installation but I get this error:

```
WARNING: incompatible requirements for package 'tensorflow' detected!
      source    package version   pip
1 deepredeff tensorflow   2.0.0 FALSE
2 tensorflow tensorflow      NA  TRUE
WARNING: tensorflow [2.0.0] will be used.

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'str' object has no attribute 'decode'

Detailed traceback:
  File "/home/rstudio-user/.local/share/r-miniconda/envs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/rstudio-user/.local/share/r-miniconda/envs/r-reticulate/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))

```

Have done something wrong with the installation of the dependencies? I had many problems with the installation of the right version in the right place of TensorFlow so I used RStudio Cloud and it allowed me to reach this point. 
Any help will be much appreciated, thank you in advance.

**Comment by JanaSperschneider** [comment]
Hi,

I have the exact same problem on RStudio (Windows). Tensorflow installed without any problems, but when running the example provided by deepredeff I get this:

```
pred_result <- deepredeff::predict_effector(
+   input = input_aas,
+   taxon = "fungi"
+ )
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'str' object has no attribute 'decode'

Detailed traceback:
  File "C:\Users\spe12g\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow_core\python\keras\saving\save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "C:\Users\spe12g\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow_core\python\keras\saving\hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
```

The Fasta file is fine and can be converted to a dataframe without problems:

```
input_aas <- Biostrings::readAAStringSet(fasta_path)
input_df <- aasset_to_df(input_aas)
```

When I supply the function pred_result with the FASTA dataframe I get this:
```
pred_result <- deepredeff::predict_effector(
+   input = input_df,
+   taxon = "fungi"
+ )
Error: Must extract column with a single valid subscript.
x Subscript `var` has the wrong type `function`.
i It must be numeric or character
```

**Comment by ruthkr** [comment]
Hi @emilecg and @JanaSperschneider, 

I am very sorry for noticing the issues just now. I have been quite busy. 
I will have a look at the issue, and try to find a fix. 

Thank you very much for reporting the issues.

**Comment by ruthkr** [comment]
Hi, @emilecg and @JanaSperschneider,

The issue was caused by breaking changes in `h5py>3`. I've updated my code to make sure `h5py==2.10.0` is installed.

To make sure the `r-reticulate` environment is installed from scratch, you will need to do the following:
- Run `reticulate::conda_list()` to get the path of installation of the `r-reticulate` environment:
![image](https://user-images.githubusercontent.com/38610118/124995987-1c2a6000-e040-11eb-94c3-7dd6801f3f88.png)
- Remove the directory (excluding `/bin/python`). For instance, following my example above:
  ```sh
  rm -rf /Users/kristiar/Library/r-miniconda/envs/r-reticulate
  ```
- Install the development version of {deepredeff} (I'll update the version on CRAN as soon as possible):
  ```r
  # install.packages("devtools")
  devtools::install_github("ruthkr/deepredeff")
  ```
- Use the helper function from {deepredeff} to install TensorFlow:
  ```r
  library(deepredeff)
  install_tensorflow()
  ```
  
Please let me know if you need any help with these steps or if you encounter any other issue (opening a new issue on GitHub). 

Thank you very much!
