### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :    AttributeError: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by bsalehe** [ruthkr/deepredeff#2]
I am getting this python function error when I run this command `predict_effector(input = "sequence.fasta", taxon = "bacteria")`. The detailed traceback is:

`Detailed traceback:
  File "/home/jr907797/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model

    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/jr907797/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 166, in load_model_from_hdf5
    model_config = json.loads(model_config.decode('utf-8'))
`

When I did few google search I decided to install reticulate package and run this command:

`reticulate::virtualenv_remove(packages="h5py", envname = "r-reticulate")`. This command gives another error which is: 'Error: Virtual environment 'r-reticulate' does not exist.'

Is it a bug? Please, is there any way to solve this issue?

Thank you

**Comment by ruthkr** [comment]
Hi @bsalehe, 

Thank you very much for reporting the issues.
I will have a look at the issue, and try to find a fix.

**Comment by bsalehe** [comment]
Eagerly waiting. Thank you.

**Comment by ruthkr** [comment]
Hi, @bsalehe,

The issue was caused by breaking changes in `h5py>3`. I've updated my code to make sure `h5py==2.10.0` is installed.

To make sure the `r-reticulate` environment is installed from scratch, you will need to do the following:
- Run `reticulate::conda_list()` to get the path of installation of the `r-reticulate` environment:
![image](https://user-images.githubusercontent.com/38610118/124995987-1c2a6000-e040-11eb-94c3-7dd6801f3f88.png)
- Remove the directory (excluding `/bin/python`). For instance, following my example above:
  ```sh
  rm -rf /Users/kristiar/Library/r-miniconda/envs/r-reticulate
  ```
- Install the development version of {deepredeff} (I'll update the version on CRAN as soon as possible):
  ```r
  # install.packages("devtools")
  devtools::install_github("ruthkr/deepredeff")
  ```
- Use the helper function from {deepredeff} to install TensorFlow:
  ```r
  library(deepredeff)
  install_tensorflow()
  ```
  
Please let me know if you need any help with these steps or if you encounter any other issue (opening a new issue on GitHub). 

Thank you very much!

**Comment by bsalehe** [comment]
I understand you closed this issue. The installation went well as you explained, but when I try to run the tool in the cluster I get the below error:

`> predict_effector(input = "/data/scratch/bsalehe/prokka_out/ps_annotation/PROKKA_07082021.faa", taxon = "bacteria")`
WARNING: incompatible requirements for package 'tensorflow' detected!
      source    package version   pip
1 deepredeff tensorflow   2.0.0 FALSE
2 tensorflow tensorflow      NA  TRUE
WARNING: tensorflow [2.0.0] will be used.
2021-07-09 14:30:59.066964: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099825000 Hz
2021-07-09 14:30:59.070300: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5589b8b41170 executing computations on platform Host. Devices:
2021-07-09 14:30:59.070359: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Loaded models successfully!
Model used for taxon bacteria: ensemble_weighted.
Terminated

Please can you assist on this?

Thank you very much

**Comment by bsalehe** [comment]
Hi @ruthkr,

I think the problem is that the fasta file is huge or something wrong with the fasta file. I run using different fasta file with small size, it just run well. So i think to run it in the different node with much more computing power.

It worked anyway! 
Thank you very much
